<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="divyaprakashAmar" failures="0" tests="4" name="practice.Test.SampleReportTest" time="1.238" errors="1" timestamp="2024-05-09T12:38:31 IST" skipped="3">
  <testcase classname="practice.Test.SampleReportTest" name="CreatecontactwithOrganiTest" time="0.009">
    <skipped/>
  </testcase> <!-- CreatecontactwithOrganiTest -->
  <testcase classname="practice.Test.SampleReportTest" name="configBS" time="1.228">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.reporter.ExtentSparkReporter.config()&quot; because &quot;this.spark&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.reporter.ExtentSparkReporter.config()" because "this.spark" is null
at com.comcast.crm.generic.fileutility.BaseClass.configBS(BaseClass.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:358)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- configBS -->
  <testcase classname="practice.Test.SampleReportTest" name="CreatecontactwithPhoneTest" time="0.000">
    <skipped/>
  </testcase> <!-- CreatecontactwithPhoneTest -->
  <testcase classname="practice.Test.SampleReportTest" name="CreatecontactTest" time="0.001">
    <skipped/>
  </testcase> <!-- CreatecontactTest -->
</testsuite> <!-- practice.Test.SampleReportTest -->
